keyspaces-cdc-streams{    
        
        stream {
           application-name = "keyspaces-stream-example"
           kcl-region = "us-east-1"
   
          keyspace-name = "media"
          table-name = "movies"
          region = "us-east-1"
          application-name = "keyspaces-vector-example"
        #stream-arn = "arn:aws:kinesis:us-east-1:123456789012:stream/keyspaces-stream"
        
        #s3 vector connector
        connector {
            target-mapper = "software.amazon.ssa.streams.connector.s3vector.S3VectorTargetMapper"
            bucket-id = "movie-vector-bucket"
            region = "us-east-1"
            max-retries = 3
            embedding-model = "amazon.titan-embed-text-v2:0"
            index-name = "movie-vector-index"
            embedding-field = "overview"
            key-field = "title"
            metadata-fields = ["title", "overview", "original_lang", "rel_date", "popularity", "vote_count"]
            dimensions = 256
        }
    }
    
    coordinator {
        skip-shard-sync-at-worker-initialization-if-leases-exist = true
        parent-shard-poll-interval-millis = 1000
        shard-consumer-dispatch-poll-interval-millis = 500
    }
    lease-management {
        shard-sync-interval-millis = 60000
        leases-recovery-auditor-inconsistency-confidence-threshold = 3
        leases-recovery-auditor-execution-frequency-millis = 5000
        lease-assignment-interval-millis = 1000
    }
    processor {
        call-process-records-even-for-empty-record-list = true
    }
}

